# Generated by Django 3.2.7 on 2023-01-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(default=11, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='products',
            name='Directions',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='Warnings',
            field=models.CharField(max_length=500),
        ),
    ]
