# Generated by Django 3.2.7 on 2023-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='media')),
            ],
        ),
    ]
